### ISSUE TITLE
Group and Notifications Endpoints Tracker

### ISSUE THREAD

**Issue by ridhishjain** [Cyber-Labs/cl-judge#37]
### `notifications` table
- [x] id (primary key)
- [x] heading
- [x] description  (optional, will contain link in markdown)
- [x] created_at
- [x] creator 

### `user_notifications` table
- [x] id (primary key)
- [x] username (foreign key from user table)
- [x] notification_id (foreign key from notification table)
- [x] read (boolean)

### Notifications API (all users)
Frontend would provide only access_token of the user in request
- [x] **`GET /notifications?limit=3`**:  Get the most recent 3 notifications of the user
- [x] **`GET /notifications`**: Get all the notifications for the user
- [x] **`POST /notifications` Admin Only**: Create a new notification, may be public or with some `target_usernames` 
- [x] **`GET /notifications/creator_notifications` Admin Only**: Get all the notifications created by the user

### `groups` table
- [x] id (primary key)
- [x] group_name
- [x] confidential (boolean)
- [x] creator (username of the creator of the group, as there can be multiple admins in a particular group)
- [x] member_count (number of members of that group)

### `user_groups` table
- [x] id (primary key)
- [x] username (foreign key from user table)
- [x] group_id (foreign key from group table)
- [x] is_group_moderator (boolean)

### Groups API
The frontend would need to provide the access_token of user in the header of each of the requests

- [x] **`POST /groups/` Admin only**: Frontend would send `group_name`, `confidential` and `usernames` ( a JSON array of usernames to be added in that group ). The array may be empty.
- [x] **`DELETE /groups/:group_id` Admin only**: Only the creator should be able to delete a group.
- [x] **`POST groups/:group_id/branch` Moderator only**: receive a `branch` code, a `department` code and an `admission_year` . Users who are having those branch code, department code, and admission_year and not present in the group already, should be added to the group
- [x] **`DELETE groups/:group_id/branch` Moderator only**: receive a `branch` code, a `department` code and an `admission_year` . Users who are having those branch code, department code, and admission_year and present in the group, should be removed from the group

- [x] **`POST groups/:group_id/members` Moderator only**: receive a JSON array of usernames to be added in the group with id as `group_id`.

- [x] **`DELETE groups/:group_id/members` Moderator only**: receive a JSON array of usernames to be removed in the group with id as `group_id`.

- [x] **`POST groups/:group_id/moderator` Moderator only**: receive `username` who should be made an admin ( A group admin can create more group admins or remove group admins, except the creator of the group)

- [x] **`DELETE groups/:group_id/moderator` Moderator only**: receive a username who should be removed from admin

- [x] **`POST groups/:group_id/update` Moderator only**: receive a new `group_name`, which should be updated.

- [x] **`GET /groups`**: all non-confidential groups in which the user is present.

- [x] **`GET /groups/moderator_groups` Moderator only**: all (confidential and non-confidential) the groups in which the user is present as a moderator. This should contain `group_name`, `creator` and `member_count` of the groups.

- [x] **`GET /groups/:group_id`**: specific group (must be non-confidential for normal user, doesn't matter if moderator) with `group_name`, `creator` and a list of `members` of the group. Each member object have the fields - `fullName`, `username`, `isGroupModerator`, `profileImg`.

**Comment by ridhishjain** [comment]
Issue to be closed only when all checks are completed

**Comment by cjchirag7** [comment]
we can add `admission_number` too in users field, as it would be used for evaluation, by the professors.

`GET /groups/:group_id`: specific group (must be non-confidential for normal user, doesn't matter if moderator) with group_name, creator and a list of members of the group. Each member object have the fields - fullName, username, isGroupModerator, profileImg, admission_number.

**Comment by ridhishjain** [comment]
I dont think it would matter.....because we have usernames in our list....

by clicking on specific that, i think we can directly jump on to the particular user's profile (the profile which will be visible to all) (API too be made later)
We can show year in that

**Comment by cjchirag7** [comment]
We can keep a variable MANAGER_USERNAME in .env file, it can be for example "Cyberlabs". For automatic notifications to be sent, the creator would be this username

**Comment by ridhishjain** [comment]
Completed, closing! :small_airplane: !!
