### ISSUE TITLE
Contests and Questions tracker

### ISSUE THREAD

**Issue by ridhishjain** [Cyber-Labs/cl-judge#60]
### `contests` table
- [ ] id (primary key)
- [ ] show_leaderboard (tiny int, 0/1)
- [ ] 
- [ ] 
- [ ] 
- [ ] 
- [ ] 
- [ ] 
- [ ] 
### `contests_groups_map` table
- [x] id (primary key)

### `contests` table
- [x] id (primary key)

### `contests` table
- [x] id (primary key)

### `contests` table
- [x] id (primary key)

### `contests` table
- [x] id (primary key)

### `contests` table
- [x] id (primary key)

### `contests` table
- [x] id (primary key)

### `contests` table
- [x] id (primary key)

### `contests` table
- [x] id (primary key)

### `contests` table
- [x] id (primary key)

### Groups API
The frontend would need to provide the access_token of user in the header of each of the requests

- [x] **`POST /groups/` Admin only**: Frontend would send `group_name`, `confidential` and `usernames` ( a JSON array of usernames to be added in that group ). The array may be empty.
- [x] **`DELETE /groups/:group_id` Admin only**: Only the creator should be able to delete a group.
- [x] **`POST groups/:group_id/branch` Moderator only**: receive a `branch` code, a `department` code and an `admission_year` . Users who are having those branch code, department code, and admission_year and not present in the group already, should be added to the group
- [x] **`DELETE groups/:group_id/branch` Moderator only**: receive a `branch` code, a `department` code and an `admission_year` . Users who are having those branch code, department code, and admission_year and present in the group, should be removed from the group

- [x] **`POST groups/:group_id/members` Moderator only**: receive a JSON array of usernames to be added in the group with id as `group_id`.

- [x] **`DELETE groups/:group_id/members` Moderator only**: receive a JSON array of usernames to be removed in the group with id as `group_id`.

- [x] **`POST groups/:group_id/moderator` Moderator only**: receive `username` who should be made an admin ( A group admin can create more group admins or remove group admins, except the creator of the group)

- [x] **`DELETE groups/:group_id/moderator` Moderator only**: receive a username who should be removed from admin

- [x] **`POST groups/:group_id/update` Moderator only**: receive a new `group_name`, which should be updated.

- [x] **`GET /groups`**: all non-confidential groups in which the user is present.

- [x] **`GET /groups/moderator_groups` Moderator only**: all (confidential and non-confidential) the groups in which the user is present as a moderator. This should contain `group_name`, `creator` and `member_count` of the groups.

- [x] **`GET /groups/:group_id`**: specific group (must be non-confidential for normal user, doesn't matter if moderator) with `group_name`, `creator` and a list of `members` of the group. Each member object have the fields - `fullName`, `username`, `isGroupModerator`, `profileImg`.

**Comment by ridhishjain** [comment]
@cjchirag7 @NBNARADHYA see if it's fine

**Comment by cjchirag7** [comment]
Suggested changes :
1. We need 1 more field in submissions table -
`judged` (tinyint - default 0)
This will show whether the submission is  judged or not (mainly for coding questions, this would be needed)

2. In contests table, we can have a field -
`confidential_questions` (tinyint - default 0)
Because sometimes the user may want that the questions of a contest should not be visible to anyone after the contest. Like for  a recruitment test of club. But for other contests, the tendency can be to move the questions of past contests to practice section.

3. In the endpoint `GET /contests?active=1&past=1&upcoming=1&limit=5` : 
The response should be like :
{
 "active": [...array of max 5 active contests],
 "past": [...array of max 5 past contests],
 "upcoming": [...array of max 5 upcoming contests], 
}

4. In `GET /contest/:contest_id/submissions?user=username` Only admin or the user with username `username` :  See all submissions of the user `username`. He should not be allowed to see other's submissions directly. If no query parameter is passed and if admin has sent the request, he should receive all the submissions of that contest.

5. In `GET /contest/:contest_id/submissions/:submission_id` It should be both, by the admin of that contest as well as the user who made that particular submission.

Rest looks good to me.

**Comment by NBNARADHYA** [comment]
@ridhishjain  main table headers as checkboxes instead of individual fields looks cleaner I think ?

**Comment by NBNARADHYA** [comment]
@ridhishjain Also could you keep the tables task in another issue ? and assign it to me also give edit access to me so that I can make changes to issue as and when I create tables and make PRs ?

**Comment by NBNARADHYA** [comment]
@ridhishjain  Could u make those checkboxes as well? Table names ?

**Comment by ridhishjain** [comment]
working on it

**Comment by ridhishjain** [comment]
> 3\. In the endpoint `GET /contests?active=1&past=1&upcoming=1&limit=5` :
>     The response should be like :
>     {
>     "active": [...array of max 5 active contests],
>     "past": [...array of max 5 past contests],
>     "upcoming": [...array of max 5 upcoming contests],
>     }
> 4\. In `GET /contest/:contest_id/submissions?user=username` Only admin or the user with username `username` :  See all submissions of the user `username`. He should not be allowed to see other's submissions directly. If no query parameter is passed and if admin has sent the request, he should receive all the submissions of that contest.
> 5\. In `GET /contest/:contest_id/submissions/:submission_id` It should be accessible both, by the admin of that contest as well as the user who made that particular submission.

these changes are incorporated

**Comment by cjchirag7** [comment]
We need the following endpoints for tags -
1. POST '/tags' - (admin only) create a tag
2. GET '/tags?search=keyword' - search for a tag

**Comment by ridhishjain** [comment]
added

**Comment by NBNARADHYA** [comment]
@ridhishjain  change getModeratorQuestions to getEditorQuestions

**Comment by cjchirag7** [comment]
Once these endpoints are completed, we can also create an endpoint to download the whole leaderboard data of a contest as "CSV" and the details of all group members as "CSV", using [csv-express](https://www.npmjs.com/package/csv-express)

**Comment by ridhishjain** [comment]
Yeah once getter APIs get merged, i'll update the checks here and apis in postman as welll

**Comment by cjchirag7** [comment]
For generating, automatic notifications, when someone is added / removed from a group, we can generate automatic notifications using MySQL Triggers - [AFTER DELETE Trigger](https://www.mysqltutorial.org/mysql-triggers/mysql-after-delete-trigger/) and [AFTER INSERT TRIGGER](https://www.mysqltutorial.org/mysql-triggers/mysql-after-insert-trigger/). I shall send it in a separate PR, later.

**Comment by ridhishjain** [comment]
Only getter for practice leaderboard is remaining as of now.
